### ISSUE TITLE
QCNN の実装

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#102]
https://arxiv.org/abs/1810.03787 の実装。Adaptive な ParametricGate が必要になるので、もしかしたら qulacs を拡張する必要があるかもしれない。

**Comment by WATLE** [comment]
古典畳み込みと量子機械学習のハイブリッドではなく、　量子で畳み込みするのか...(驚愕)NISQデバイスで可能だろうか?

それはともかく、「一つのラーニングパラメーターが複数のゲートに同時作用する」はたしかに対応していないから拡張が必要ですね。

LerningCircuitクラスを拡張するか、QCNN(Classfier,regressor)クラスを作成するかが必要だと思います。

「測定して、その結果に応じてほかのゲートを回す」はCNOTと回転ゲートで可能でしたっけ?(量子にあまり詳しくないので)

**Comment by kosukemtr** [comment]
参考：https://www.tensorflow.org/quantum/tutorials/qcnn?hl=ja

**Comment by forest1040** [comment]
forest1040こと森俊夫と申します。
宜しくお願い致します。

まだ途中のQNNClassifierを使ったベタ書き実装ですが、TFQをscikit-qulacsで実装したコードを
以下にpushしております。
https://github.com/forest1040/beta-qcnn/blob/master/qc.py

以下のような形で実行でき、精度としては「0.9790616888074514」出ております。

```
$ python qc.py
trained parameters:  [ 0.55465653  2.82311861  0.7220556   0.03930114  2.98778973  2.23557833
  0.01171408  0.35997806  1.44507332 -2.06321159  0.52103661  0.05433799
 -1.88497743 -3.02521679  0.7936977   0.22392469 -0.69022145  2.68971409
  0.7044144   0.03183893 -2.10678875  0.76327131  0.57722859  0.23789282
  2.72824701  0.71606922  0.5356328   0.58990998]
loss:  0.44736107090311494
f1_score:  0.9790616888074514
```
こちらを整理してクラス化していこうと考えています。

量子のクラスター状態の回路がこれでよいのか自信がない所ですが。。
TFQのデータ生成と回路を見た感じで移植しています。
生成したデータの回転角を8bit分、RXゲートで持たせています。
同じデータを8bit分持たせるので合っているのか、確認中です。

以下、思った事です。
- TFQの実装について
- Cirqを今回初めて触ったため、手探りで調査しました。。
- 最初、なぜCirqでは畳み込み回路を回転ゲートを使わずに基本ゲートに対して、指数で設定しているのが疑問でした。
  - どうやらCirqでは変分回路を実装しよとすると指数指定しないとパラメータ化できないようでした。
  - 我々には、LearningCircuitがあるので、回転ゲートでパラメータ化できますね！
- CZゲートを使わない理由。
  - 恐らくですが、CZゲートは重いため、他のゲートに分解しているかと思っています。確認中です。
- 他論文の参照
  - 以下の論文も参照し実装中です。
  - https://arxiv.org/abs/2108.00661
  - Pennylaneを使った量子畳み込みの実装です。
  - 9+αの畳み込み回路と複数のエンコードパターンで精度を比較しています。
  - 現状、一番簡単な畳み込み回路で実装しています。
  - 他の畳み込み回路も実装中ですが、LearningCircuitにCZやパラメータ付きの制御回転回路がないため、追加するか別のゲートに展開するか検討中です。
  - 余力があれば、この論文と同じように画像に対して、QCNNをかけて性能比較をしたいと考えています。
- プーリング回路について
  - クラスター状態ですので、近接している箇所をプーリングしていくのがよいかなと思いましたが、いきなり下に寄せても精度はそれほど変わりませんでした。
  - プーリング回路もベタ書きですので、これから整理していく途中です。
  - 参照論文ではプーリング回路も3パターン程度ありました。また回路規模が大きくなれば、最大値/最小値を取るとか合算する等、回路を複雑にしていけたらよいなと思っています。

**Comment by WATLE** [comment]
複数のゲートがひとつの変数を共有するわけではないんですか？
てっきり「畳み込み」だからそういう要素があるものだと思ってました...

**Comment by WATLE** [comment]
しかし、複数のゲートがひとつの変数を共有するゲートは現状scikit-qulacsに存在しません。(新規実装が必要)
LearningCircuitにCZを使いたいなら、add_gate(CZ(target,control))　でできるはずです(ほとんどすべてのゲートを、add_gate()関数でLearningCircuitに入れられます

パラメータ付きの制御回転回路,　一応add_parametric_input_RX_gate() が可能かと思われますが、backpropに対応してないのでsolverがNelder-Meadになり、相当遅くなるのでやっぱりダメっぽいです

**Comment by kosukemtr** [comment]
@forest1040 
御手洗です。ありがとうございます & 返信が遅くなって失礼しました。

> 最初、なぜCirqでは畳み込み回路を回転ゲートを使わずに基本ゲートに対して、指数で設定しているのが疑問でした。

これはforest1040さんのおっしゃる通りかと思います。

> CZ ゲートを使わない理由

これはどこの CZ ゲートのことを指しているでしょうか？

> LearningCircuitにCZやパラメータ付きの制御回転回路がないため

CZゲートに関してはWATLEさん  (プログラミングバイトとして雇用している学生です。) の仰るとおりです。パラメータ付きの制御回転ゲートについては、２つの対応策が考えられます。
- LearningCircuit というか LearningCircuit がラップしている qulacs-osaka の ParametricCircuit にも機能が存在しないので、qulacs-osaka の ParametricCircuit を触って機能追加していただかないといけないです。この場合 backprop を使いたければ、追加したパラメータ付きの制御回転ゲートに対応させる必要があります。
- おっしゃるように他のゲートに分解してしまうというのもありえます。が、分解時に複数のゲートが同じパラメータを持つようにしないといけなくなるという問題があります。

個人的には次の点も踏まえて2番目の方針で実装するのが良いかと考えています・

WATLEさんがおっしゃっているように、原論文 (https://arxiv.org/pdf/1810.03787.pdf) のQCNN は同一レイヤー内の各2量子ビットゲートや pooling の回転角に同じものを使うという事になっています。TensorFlow Quantum のほうでも sympy を利用してそれを実現しているようです。これを踏まえて、LearningCircuit 自体を複数のゲートがパラメータを共有するようなものに拡張していただき、それを使って QCNN を実装していただきたいです。この機能拡張によって、パラメータ付きの制御回転ゲートも実装可能になると思います。

**Comment by totti-linkode** [comment]
WATLEさん、御手洗さん
コメントありがとうございます。

> WATLEさん
> 複数のゲートがひとつの変数を共有するわけではないんですか？
> てっきり「畳み込み」だからそういう要素があるものだと思ってました...

はい。TFQの実装は、パラメータを共有していると思います。
私の実装は、試しにパラメータ共有しない簡易版の畳み込みを実装してみました。

> LearningCircuitにCZを使いたいなら、add_gate(CZ(target,control))　でできるはずです(ほとんどすべてのゲートを、add_gate()関数でLearningCircuitに入れられます

ありがとうございます。確認します。

> パラメータ付きの制御回転回路,　一応add_parametric_input_RX_gate() が可能かと思われますが、backpropに対応してないのでsolverがNelder-Meadになり、相当遅くなるのでやっぱりダメっぽいです

なるほど。backpropの対応が必要なのですね。。


> 御手洗さん
> > CZ ゲートを使わない理由
>
> これはどこの CZ ゲートのことを指しているでしょうか？

元々の論文 https://arxiv.org/abs/1810.03787 がCZゲートを使用した畳み込み処理かなと思っております。
（私の勘違いかも知れません。）

> これを踏まえて、LearningCircuit 自体を複数のゲートがパラメータを共有するようなものに拡張していただき、それを使って QCNN を実装していただきたいです。この機能拡張によって、パラメータ付きの制御回転ゲートも実装可能になると思います。

承知しました。
今回は、一旦2x2フィルタ限定を考えておりますので、2ゲートでパラメータ共有する形で実装してみます。
ついでに余力があれば、ゲート分解もやってみたいと思います。
（PennyLaneも触らないと！）

**Comment by forest1040** [comment]
すみません。うっかり仕事アカウントで書き込んでしまったので、再送します。

WATLEさん、御手洗さん
コメントありがとうございます。

> WATLEさん
> 複数のゲートがひとつの変数を共有するわけではないんですか？
> てっきり「畳み込み」だからそういう要素があるものだと思ってました...

はい。TFQの実装は、パラメータを共有していると思います。
私の実装は、試しにパラメータ共有しない簡易版の畳み込みを実装してみました。

> LearningCircuitにCZを使いたいなら、add_gate(CZ(target,control))　でできるはずです(ほとんどすべてのゲートを、add_gate()関数でLearningCircuitに入れられます

ありがとうございます。確認します。

> パラメータ付きの制御回転回路,　一応add_parametric_input_RX_gate() が可能かと思われますが、backpropに対応してないのでsolverがNelder-Meadになり、相当遅くなるのでやっぱりダメっぽいです

なるほど。backpropの対応が必要なのですね。。


> 御手洗さん
> > CZ ゲートを使わない理由
>
> これはどこの CZ ゲートのことを指しているでしょうか？

元々の論文 https://arxiv.org/abs/1810.03787 がCZゲートを使用した畳み込み処理かなと思っております。
（私の勘違いかも知れません。）

> これを踏まえて、LearningCircuit 自体を複数のゲートがパラメータを共有するようなものに拡張していただき、それを使って QCNN を実装していただきたいです。この機能拡張によって、パラメータ付きの制御回転ゲートも実装可能になると思います。

承知しました。
今回は、一旦2x2フィルタ限定を考えておりますので、2ゲートでパラメータ共有する形で実装してみます。
ついでに余力があれば、ゲート分解もやってみたいと思います。
（PennyLaneも触らないと！）

**Comment by forest1040** [comment]
2ゲートでパラメータ共有する形で実装してみました。
https://github.com/forest1040/beta-qcnn/blob/master/qc.py
```
python qc.py
trained parameters:  [ 1.24048157 -0.40178538  1.11489332  2.7945138   3.03882061  2.28405652
 -1.875656    0.89404618 -2.800177   -1.70825989 -3.15607918  1.72270277
  0.22392469  0.23920597  2.81243215  1.36370929 -2.86027698 -1.86429968
  0.80242493  0.64465379  0.2238875   0.56492104  1.44589935 -1.18361661
 -0.55651582 -1.82868404  0.18619301  0.86443452  1.50514204 -0.05994907
 -1.7127044  -1.54342374 -2.77698469 -0.41207249 -2.01310947 -2.98653163
 -2.71905076  1.12715804 -0.29093131  0.22983396  0.89667129  0.99033895
 -1.77878871  1.02465057 -1.48708937 -3.0118386   1.62344096 -1.13086559
  0.81041682  2.34143312 -1.42287736  1.87268349 -1.97520762  2.84497389
  0.68748828  0.21550768  2.70476662  1.60603179 -1.66871807 -1.88125184
  0.12087828 -2.96717154 -0.27679364 -1.23211453  0.54528213  2.2861722
 -2.40311822  0.10919615  0.13206811  0.71685968 -0.65307615  0.41105423
 -1.99001148 -2.23148734 -0.0750446  -0.90721192  2.53664594 -2.61743403
  0.32793496  0.5307788   2.90243187 -1.30597561  0.24082878  0.10029394
 -3.03836225  2.69881229  1.06761715  1.79166859 -1.37143019  0.54293109
  2.36565223 -1.0168773   2.90013081 -1.6857684   2.82315342  2.77325791
  0.79920259  0.63044794]
loss:  1.2526048739241349
f1_score:  0.9363583138173301
```
- 取り敢えずLearningCircuitを継承した、LearningCircuitExを作成して、add_parametric_multi_Pauli_rotation_gate()を追加。
  後で、LearningCircuitクラスの方に追加する形にしたいと思います。
  https://github.com/forest1040/beta-qcnn/commit/6c49bb16376dfef5db4285b62c7488850e51753d
- Error: ParametricPauliRotation does not support backprop in parametric
  - qulacs-osakaのParametricQuantumCircuit::backprop()で、ParametricPauliRotationゲートも対象とするようにしました。
  https://github.com/forest1040/qulacs-osaka/commit/4c51baece2b4faf5bd06692ccd9502217867d8f8#diff-8a8bc3521696d2da8a9ae68493af7ec697bbce90d060e989098c84fcc8211027
  取り敢えず自分のリポジトリでの修正です。
- Pooling回路が簡易版
  - TFQ版のPooling回路にするためには、パラメータを共有して-1して戻す必要がある。。
    - TFQ版のようにパラメータをsymbolで指定できるようにする（qulacs-osakaの改修が大きそう。。）
    - アドホックに-1する対応を入れる（qulacs-osakaの改修が必要そう）

前に以下のように記載しましたが、勘違いでした。。
```
- プーリング回路について
    - クラスター状態ですので、近接している箇所をプーリングしていくのがよいかなと思いましたが、いきなり下に寄せても精度はそれほど変わりませんでした。
```
隣り合う通しを寄せていく方が精度が良いです。

**Comment by kosukemtr** [comment]
毎度毎度返信が遅くて申し訳ありません。

- multi_pauli_rotation の backprop 対応ありがとうございます！PR 投げていただければ (私か他の方が) レビューさせていただきます。
- 2パラメータを共有するという部分なのですが、どのようにそれを実現しているのかコードから読み取ることができませんでした... コードのどの部分がそれに該当するのか教えていただきたいです。
  - 関連して、「パラメータを共有して-1して戻す必要がある」という部分が何を指しているのかわかりませんでした

**Comment by forest1040** [comment]
いろいろとお忙しい時期かと思います。
ご多忙の所、回答頂き恐縮です！

> - multi_pauli_rotation の backprop 対応ありがとうございます！PR 投げていただければ (私か他の方が) レビューさせていただきます。

油断していたらupstream（Qulacs-Osaka/qulacs-osaka）の方のコードが結構変わっておりました。。
整理してPRを作成させて頂きます。
（backprop_inner_product()等が追加されており、QuantumGateBase* RcPIの設定等がされておりますので確認中です。）
整理のため、一度私の方もforkし直します。

> - 2パラメータを共有するという部分なのですが、どのようにそれを実現しているのかコードから読み取ることができませんでした... コードのどの部分がそれに該当するのか教えていただきたいです。

add_parametric_multi_Pauli_rotation_gate()で複数ゲートを追加した際に、パラメータは１個しか追加されませんでしたので共有されているものと思っております。
（qulacs-osakaの方のコードまで確認しておりませんでしたので確認しておきます。）
それを想定してですが、add_parametric_multi_Pauli_rotation_gate()で設定している
https://github.com/forest1040/beta-qcnn/blob/master/qc.py#L57
が該当箇所になります。
間違っておりましたら、修正させて頂きます。

> 関連して、「パラメータを共有して-1して戻す必要がある」という部分が何を指しているのかわかりませんでした

TFQ版のPooling回路図を添付させて頂きます。
右のRz/Ry/Rxのパラメータのシンボルが-x2/-x1/-x0となっております。
一番左で作用させたRz/Ry/Rxのパラメータの値を-1して
![TFQ-Pooling](https://user-images.githubusercontent.com/127030/154787872-07773427-3647-4c36-83dc-abbe18d748a3.svg)
逆回転させて戻しているという認識です。

**Comment by forest1040** [comment]
> - multi_pauli_rotation の backprop 対応ありがとうございます！PR 投げていただければ (私か他の方が) レビューさせていただきます。

https://github.com/Qulacs-Osaka/qulacs-osaka/pull/237
に一旦PRを作成させていただきました。
まだqulacs-osakaのコードをざっとしか見れておりませんので検討違いかも知れません。
確認をお願い致します。

**Comment by kosukemtr** [comment]
> add_parametric_multi_Pauli_rotation_gate()で複数ゲートを追加した際に、パラメータは１個しか追加されませんでしたので共有されているものと思っております。

はい、この関数はパラメータを１つしか追加しないと思います。ただこれを使うことで「2つのパラメータを共有している」ということになるのがなぜなのかがよくわかっていないです... 具体的にはどことどこのパラメータを共有していることになるのでしょうか？

**Comment by kosukemtr** [comment]
tensorflow quantum の実装をもう一度見直そうと思ったのですが、https://www.tensorflow.org/quantum/tutorials/qcnn?hl=ja がなぜかリンク切れを起こしているので、https://github.com/tensorflow/quantum/blob/master/docs/tutorials/qcnn.ipynb を見てみました。するとたしかに
```python
def two_qubit_unitary(bits, symbols):
    """Make a Cirq circuit that creates an arbitrary two qubit unitary."""
    circuit = cirq.Circuit()
    circuit += one_qubit_unitary(bits[0], symbols[0:3])
    circuit += one_qubit_unitary(bits[1], symbols[3:6])
    circuit += [cirq.ZZ(*bits)**symbols[6]]
    circuit += [cirq.YY(*bits)**symbols[7]]
    circuit += [cirq.XX(*bits)**symbols[8]]
    circuit += one_qubit_unitary(bits[0], symbols[9:12])
    circuit += one_qubit_unitary(bits[1], symbols[12:])
    return circuit
```
というのが部分があって、まさに @forest1040 さんに書いていただいている回路と (レイヤー内でパラメータの共有が行われていることを除いて) 全く同じ回路だということがわかりました。ということで、まだ「2つのパラメータの共有」が何を意図しているのかはよくわかっていないのですが、とりあえずはこの実装でもいいのかなと思いました。

**Comment by kosukemtr** [comment]
今後の方針として、
- レイヤー内でのパラメータの共有は、LearningCircuit のちょっとした拡張が必要になる気がするので、別 issue で立てようと思います。
- 原理的にはレイヤー内での共有を外したほうが、回路の表現能力が高くなって分類性能は上がるはずだと思うので、とりあえずは今の実装を整理して pre_defined circuit として scikit-qulacs に組み込み、簡単なチュートリアル用の jupyter notebook まで整備していただけると嬉しいです。
- そして後日 (いつになるかはわかりませんが)、パラメータ共有機能ができ次第、 こちらに適用するという方針にしようと思います。(もちろん上記 issue はこちらで対応します。)

このような感じはいかがでしょうか？

**Comment by forest1040** [comment]
> このような感じはいかがでしょうか？

承知しました。

- pre_defined circuit として scikit-qulacs に実装しPRを作成します。
- その後、簡単なチュートリアル用の jupyter notebook を作成します。

**Comment by forest1040** [comment]
> はい、この関数はパラメータを１つしか追加しないと思います。ただこれを使うことで「2つのパラメータを共有している」ということになるのがなぜなのかがよくわかっていないです... 具体的にはどことどこのパラメータを共有していることになるのでしょうか？

すみません。確認させてください。

TFQ版のConv部分の回路図を添付させて頂きます。
![TFQ-Conv](https://user-images.githubusercontent.com/127030/155519272-89daa89c-9563-4fd6-9fff-7c0ed139d998.svg)

2つのパラメータを共有しているのは、例えば、`XX^x8`となっているRxxゲートだと思っております。
![rxx](https://user-images.githubusercontent.com/127030/155519479-3b291434-f0f3-4adb-b5e9-2649483a9027.png)

Rxxゲートはこのような形で、同一の`θ/2`を共有しているという認識です。

`add_parametric_multi_Pauli_rotation_gate()`で、pauli_idsに[1,1]を指定すればRxxゲートでパラメータが共有されているかと思ったのですが違うでしょうか。。

**Comment by kosukemtr** [comment]
> 承知しました。

ありがとうございます。よろしくお願いします。


> Rxxゲートはこのような形で、同一のθ/2を共有しているという認識です。

なるほど！意図されていることが理解できました。ただ、通常この分野では 
<img src="https://render.githubusercontent.com/render/math?math=R_{XX}(\theta)=e^{-i\theta X\otimes X/2}">
を 1 つのパラメータ θ を持つ 1 つのゲートであると考えて、<img src="https://render.githubusercontent.com/render/math?math=R_{XX}(\theta)">
 内部でパラメータが共有されているという風に考えることは無い感じです...

**Comment by forest1040** [comment]
ありがとうございます。
パラメータ共有ではなく、1 つのパラメータ θ を持つ2量子ビットゲートであるという感じでしょうか。。
Conv層はこれでTFQ版と同等の操作になっているかと思っています。間違っていたらご指摘ください。
Pooling層は、TFQ版の場合、パラメータ共有が必要かと思いますので、qulacsの修正が必要かと思います。

**Comment by forest1040** [comment]
https://github.com/Qulacs-Osaka/scikit-qulacs/pull/143 で、pre_defined circuit に回路を追加して、一旦PRを作成しました。
test と jupyter notebook は作成中です。

**Comment by forest1040** [comment]
test と jupyter notebook を追加しました。
確認をお願い致します。

**Comment by forest1040** [comment]
ikanagoさんに以下を対応いただきましたので、pooling回路をパラメータ共有版に変更します。

- [LearningCircuit 内でのパラメータの共有 · Issue #141 · Qulacs-Osaka/scikit-qulacs](https://github.com/Qulacs-Osaka/scikit-qulacs/issues/141)
- [Share learning parameters by ikanago · Pull Request #166 · Qulacs-Osaka/scikit-qulacs](https://github.com/Qulacs-Osaka/scikit-qulacs/pull/166)

**Comment by forest1040** [comment]
https://github.com/Qulacs-Osaka/scikit-qulacs/pull/210
にて実装
