### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#109]
そろそろ「とりあえず使ってみる」という機会が増えてきたと思うので，PyPI からインストールできるようにしたほうがいいと思います．

**Comment by WATLE** [comment]
これやるなら、開発もdevブランチとmainを分けたほうがいいですか？

**Comment by ikanago** [comment]
個人的には今まで通り全てのプルリクを main にマージして，リリースしたいタイミングで `release/v0.1.0` みたいなブランチを生やしてリリース作業(バージョンのタグを打つ，リリースノートを作るなど)をすればいいかなと考えています

**Comment by kosukemtr** [comment]
個人的にはその方針で全く問題ないと思いました

**Comment by Hiroya-W** [comment]
同じく、その流れが今の開発に合っていそうな気がしています
release/v0.1.0ブランチの内容はmainブランチに取り込まれて、リリース作業終了、という感じでしょうか？

**Comment by ikanago** [comment]
そうですね，そうすると main ブランチにタグもマージされるはずなのでいい感じになると思ってます
それぞれ考えてることが微妙に違ってたらあれなので，リリース作業の案を軽くまとめてみます
