### ISSUE TITLE
PennyLane との実行時間の比較

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#116]
PennyLane や TensorFlowQuantum で同じタスクをやらせたときに、どのくらい速度差があるか知りたい。やったあと、Qulacs の Readme のようにベンチマーク結果を載せたい。

**Comment by ikanago** [comment]
やってみたいです

**Comment by ikanago** [comment]
この issue では PennyLane との比較のみ実装します．

**Comment by forest1040** [comment]
実行時間の比較とは、直接は関係ないとは思うのですが。。コメントさせて頂きます。
PennyLane ちょっと触ってて思ったのですが、バックエンドによっては、backprop が使えるようです。
https://pennylane.ai/qml/demos/tutorial_backprop.html

現状のpennylane_qulacsだと多分パラメータシフト法になると思います。
https://github.com/PennyLaneAI/pennylane-qulacs/blob/master/pennylane_qulacs/qulacs_device.py

qulacs-osakaには、WATLEさんのbackpropがあるので対応させたら面白いなと思いちょっと見てみました。
passthru_devicesとpassthru_interfaceを対応させる必要があるようです。
passthru_devicesは、単にqulacs-osakaにパススルすればいいだけの設定なのですが
passthru_interfaceをちゃんと実装しないと動かないようでした。。

**Comment by ikanago** [comment]
PennyLane 妙に遅いので別の issue で backprop 試してみようと思います．ありがとうございます 🙏

**Comment by forest1040** [comment]
取り敢えずdefaultのpennylane-lightningで、adjointを使うのがてっとり早いかも知れません。。
https://github.com/PennyLaneAI/pennylane-lightning
https://qiita.com/notori48/items/e16daf8da8b63a199d96
