### ISSUE TITLE
dev-container で volume を使う

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#120]
仮想環境を Docker の volume にするとインストールが高速になります．
参考: https://code.visualstudio.com/remote/advancedcontainers/improve-performance

**Comment by ikanago** [comment]
たしかに .venv を volume mount にすると `poetry install` が高速になった．
bind マウントで作った

**Comment by ikanago** [comment]
[ワークスペース全体を volume マウントできる](https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-a-named-volume-for-your-entire-source-tree)ので試してみました．

devcontainer.json に以下のような設定を書きます．
```json
"workspaceMount": "${localWorkspaceFolderBasename}-volume,target=/workspace,type=volume"
"workspaceFolder": "/workspace",
```
そのあとリポジトリを `git clone` します．このとき `/workspace` のオーナは root なので `chown` する必要があります．
ただ，あくまで `workspaceFolder` は `/workspace` なので，ワークスペースを開くとリポジトリの1つ上のディレクトリになってしまいます．

これを回避するために `"workspaceFolder": "/workspace/scikit-qulacs",` とすると，ディレクトリがないので怒られます．
そこで Dockerfile を以下のようにしてこのディレクトリをあらかじめ用意しておきます．
```Dockerfile
USER vscode

RUN sudo mkdir -p /workspace/scikit-qulacs && sudo chown vscode /workspace/scikit-qulacs
```

こうすると `git clone` したあと `chown` する必要もなくなるのですが，かえってややこしいのでワークスペースは bind mount でもいいのでは?となっています

**Comment by Hiroya-W** [comment]
> ただ，bind mount で作った .venv が存在しても volume mount の .venv が正常に mount されていて，これは想定される挙動なのかが気になります．

ドキュメントをすぐには提示できないんですが、僕はこれは想定される挙動だと思って使っていました。

**Comment by ikanago** [comment]
ワークスペース全体を volume mount する利点:
* ファイル IO が bind mount より速くてうれしい
* ローカルのリポジトリと Docker 上のリポジトリを明示的に分けられる

微妙な点:
* 設定が多少増える
* 依存パッケージのインストール高速化ほどの恩恵は薄そう

**Comment by ikanago** [comment]
> ドキュメントをすぐには提示できないんですが、僕はこれは想定される挙動だと思って使っていました。

確かに mount の仕組みを考えるとそんな気はしますね...
これを利用すればコンテナ内外で .venv を分けられるので移行が楽そうです．

**Comment by Hiroya-W** [comment]
そのワークスペースをdevcontainerで開くという操作は、ローカルのファイルがbind mountされる、とするのが使い方としては分かりやすい気がします。
ワークスペース全体をVolume mountする場合、ただソースコードを見たいだけなのに、Dockerコンテナ内にアタッチしないといけなくなるのも不便かもですね。

**Comment by Hiroya-W** [comment]
利点と微妙な点の調査、ありがとうございます！
設定が複雑になるコストと、その恩恵を考えると、Volume mountするのは`.venv`だけで十分かな、と感じました。

**Comment by kotamanegi** [comment]
Volumeマウントは言うなら違うストレージを持っているようなものなので、知らない人にとってはbindマウントと比べて非直感的な動作をすると思います。
実際のフォルダを操作するようにしておけば、いざとなった時にOS標準のファイラー(エクスプローラー)でデータを見たりできますしbindマウントの方が良いと感じました。 
ユーザが直接管理しないようなものはVolumeマウントの方が良いのですが、設定の手間を考えると`.venv`だけで良さそうです。
