### ISSUE TITLE
スケーリングの処理を class に切り出す

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#140]
スケーリングのコードが重複しているため，class(あるいは関数) として切り出したほうがいいと思います．

**Comment by ikanago** [comment]
scikit-learn にあるやつを使うのもよさそうです: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler

**Comment by kosukemtr** [comment]
classifier 内部のスケーリングは関数名とは全く違う処理をしていそうなので、共通化というより classifier のスケーリング関数の名前変更が必要そうです

**Comment by ikanago** [comment]
scikit_learn に one-hot 化と逆変換をやるやつがあるのでその辺の処理は自前でやらなくてよさそうです
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

**Comment by WATLE** [comment]
これ実装しますｓ

**Comment by WATLE** [comment]
one-hotすごいな　ほかにもこういうすごいのあるかも　scikit_learnのPreprocessing　に目を通します

**Comment by WATLE** [comment]
one-hotと逆変換はできても、softmaxと確率表示ができないのが気になります。

**Comment by ikanago** [comment]
#149
