### ISSUE TITLE
LearningCircuit 内でのパラメータの共有

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#141]
ある parametric gate と別の場所の parameteric gate に同じパラメータを使えるようにしたいです。(#102 で必要。) 幸い `_Parameter` クラスがいい感じに使えそうなので、`add_parametric_..._gate()` に `share_parameter_with: int` のようなオプションを追加すれば機能的には実装できそうですがいかがでしょうか @ikanago 。あとは backprop を書き換えるだけな気がします。

**Comment by ikanago** [comment]
`ParametricQuantumCircuit` のパラメータのうち共有したいパラメータを指す `_Parameter` を作るようにすればたしかに実装できそうです．

**Comment by kosukemtr** [comment]
>c++のbackpropを書き換えなくても、LerningCircuitのbackpropをうまくやって

そのとおりだと思います。なのでそんなに大変じゃないですね。
