### ISSUE TITLE
QCL ansatz の preprocess_x で入力データを [-1,1] にクリップするときに警告を出す or やめる

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#142]
https://github.com/Qulacs-Osaka/scikit-qulacs/blob/4745c4b3cf98bc87d482d58b1c639c447198da6b/skqulacs/circuit/pre_defined.py#L28
で入力データが [-1,1] の範囲外にあるとき arcsin がエラー出してしまうのを防止するために [-1,1] にクリップしていますが、暗にやられるとユーザーが困るときがあるのでその場合は警告を出すようにする。

もしくはそもそも arcsin でエラーが出るはずなので、preprocess をやめてしまって、arcsinにエラーを出させたほうが安全かもしれない。

個人的には後者がいいと思ってます。

**Comment by ikanago** [comment]
たしかに勝手にクリップするのはよくないので preprocess はやめてしまってよさそうです．

このあたりは #140 でも似たようなことを考えていました．
`QNNClassifier` などの学習器か `LearningCircuit` に対してデータのスケーリングをする関数かクラスを渡すと今の `preprocess` に相当する処理をやってくれる，みたいにすると何もしないケースを含めてあらゆるスケーリングに太王できると思います．
雰囲気としてはこんな感じです:
```python
class MinMaxScaler(Scaler):
    """Perform Min-Max scaling against every input/output data."""
    ...

qcl = QNNClassifier(circuit, num_class, "Adam", MinMaxScaler())
```

**Comment by WATLE** [comment]
現在、データをtrainするときの最大値と最小値で[-1,1]を決める実装になっています。
当然、testでtrainの範囲を超過することはよくありますが、そうしたときエラー吐くのは困ります。

**Comment by kosukemtr** [comment]
test だけで超過する場合に対応しようとするとたしかにそうですね。なので1を超えちゃうときは警告出して clip するようにしましょうか

**Comment by WATLE** [comment]
警告出すのはいい案ですね。

**Comment by WATLE** [comment]
それと、そもそもarcsinを使うべきではないという話もあります。なぜなら[-1,1]の両端近辺だけ微分値が非常に大きくなるからです

**Comment by WATLE** [comment]
半分理解して、半分違和感があります。
量子状態の振幅の実数部分はsin(x)だからarcsin(x)が必要だというのは理解できます。
しかし、回転なので、虚数部分ではxの両端付近が非常に多く動く気もします。

いろんなオプションを用意するのはよさそうです。

**Comment by WATLE** [comment]
MinMaxScaler、QNNClassifierに渡す引数が多すぎるような気もしなくはないです

**Comment by ikanago** [comment]
> QNNClassifierに渡す引数が多すぎる

`num_class` は使ってなさそうなので削ってよくて， circuit と optimizer と scaler だけになるのでそこまで多くならなさそうです

**Comment by WATLE** [comment]
num_class使ってない、本当ですね　消しましょう

**Comment by WATLE** [comment]
リファクタリングにより、num_classを使うようになりました
