### ISSUE TITLE
early_stopping

### ISSUE THREAD

**Issue by kenjikun** [Qulacs-Osaka/scikit-qulacs#144]
古典の機械学習ではearly_stoppingを多用するので、scikit-qulacsにもearly_stoppingがあると便利だと思います。
scipyのminimizeだとcallbackを設定できるのでそれを使って実装するのはどうでしょうか。

**Comment by WATLE** [comment]
early_stoppingの条件とかは、大体scikitのニューラルネットワークライブラリ
https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html#sklearn.neural_network.MLPRegressor
でいいですか？

**Comment by WATLE** [comment]
方針：costの減少量がtol　未満の改善が、n_iter_no_change　回続いたら、強制終了
問題点: sckitではearly_stoppingはBFGSに対応していない。
BFGSのアルゴリズムをよく知らないが、おそらくBFGSではアルゴリズム上、early_stoppingが不可能なのではないか？
その場合、結局callbackを設定してearly_stoppingは不可能になる。

Adamは自前実装で、scikitでもearly_stopping対応なので、　Adamに限ってearly_stoppingするなら簡単である。

**Comment by WATLE** [comment]
early_stoppingをどうやってテストするか今考えています。
行ったepoch数を返す実装になってないので、どうしましょう？

**Comment by kenjikun** [comment]
> 方針：costの減少量がtol　未満の改善が、n_iter_no_change　回続いたら、強制終了 問題点: sckitではearly_stoppingはBFGSに対応していない。 BFGSのアルゴリズムをよく知らないが、おそらくBFGSではアルゴリズム上、early_stoppingが不可能なのではないか？ その場合、結局callbackを設定してearly_stoppingは不可能になる。
> 
> Adamは自前実装で、scikitでもearly_stopping対応なので、　Adamに限ってearly_stoppingするなら簡単である。

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
scipyのminimizeで実装していれば、callbackを設定すればearly_stoppingが可能です。

**Comment by kenjikun** [comment]
> early_stoppingをどうやってテストするか今考えています。 行ったepoch数を返す実装になってないので、どうしましょう？

https://github.com/scikit-learn/scikit-learn/blob/9816b35d05e139f1fcc1a5541a1398205280d75a/sklearn/neural_network/tests/test_mlp.py#L797

scikit-learnのテストでは内部のカウンタを参照して意図したステップで止まっているかを確認しているようです。

**Comment by ikanago** [comment]
#154
