### ISSUE TITLE
log_loss miss

### ISSUE THREAD

**Issue by WATLE** [Qulacs-Osaka/scikit-qulacs#148]
log_lossの微分計算ミスってたことが発覚

**Comment by WATLE** [comment]
log_lossそのものを勘違いしていた模様。原因不明
かすかな記憶として、regとの対称性とか、正規化とか、出力が[-1,1]しか取れないとかあった気もしなくはない。
とりあえず、修正します

**Comment by WATLE** [comment]
https://www.iwanttobeacat.com/entry/2018/08/26/225822

**Comment by WATLE** [comment]
https://www.anarchive-beta.com/entry/2020/08/06/180000

**Comment by WATLE** [comment]
直したらスコア下がっりました　直したつもりがバグを埋め込んだだけかもしれませんけど。

**Comment by WATLE** [comment]
どうします？

**Comment by WATLE** [comment]
@ikanago

**Comment by ikanago** [comment]
実装見たいので push してもらえますか(すでに上げてて見つけられてないだけだったらすいません)?

**Comment by WATLE** [comment]
実験したところ、計算方法が異なったことにより、最適なパラメータが変化していました。
具体的には、y_exp_ratioを5.0から2.2に下げることで成功しました。

pushします

**Comment by ikanago** [comment]
#149
