### ISSUE TITLE
classifier,一つのQNNで同時に複数個の分類　をやめるかどうか

### ISSUE THREAD

**Issue by WATLE** [Qulacs-Osaka/scikit-qulacs#151]
例えば、[入力データ１] = [犬,オス] 、　[入力データ2] = [猫、メス] [入力データ3] = [猫、オス]
のように。
これはscikitにあるという理由で実装し、あまり使わないのでろくにテストもされていないが、後方互換性のために消すわけにもいかず、実装を複雑化させています。

**Comment by ikanago** [comment]
個人的には「実装を複雑化させていてさほどテストされていないうえにほぼ使われていない機能」よりは「ある領域のタスクは解けないが，単純な実装でテストしやすい機能」を採用すべきだと思います．
このライブラリは実用性よりも量子機械学習のプロトタイピングを目的としているはずなので，高度な機能をいくつか諦めることで他にいいことがあるならそれで問題ないと思います．

**Comment by WATLE** [comment]
OK. では、　量子一つのQNNで同時に複数個の分類をする機能を撤廃し、すべてをシンプルにします。

**Comment by ikanago** [comment]
#149
