### ISSUE TITLE
共有されているパラメータに係数をかけられるようにする

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#169]
参考:

> いいと思います！次はシェアされているパラメータに係数がかかってるみたいなのもできるといいかもしれないですー。( -RX(2*θ_1)-RZ(θ_2)-RX(0.5*θ_1)- みたいな回路を作りたいときもあるかもしれないので)

_Originally posted by @kosukemtr in https://github.com/Qulacs-Osaka/scikit-qulacs/pull/166#pullrequestreview-934548634_

**Comment by forest1040** [comment]
@ikanago すみません! QCNNで共有されているパラメータに係数をかけられる必要ありました。。
前、QCNNでは使わないと言ってしまいましたが。。
逆回転させるため、-1をかける必要がありました。
一旦、私の方で対応してみます。

**Comment by forest1040** [comment]
`_LearningParameter`クラスに`positions_in_circuit: List[int]`を持っていますが、このList[int]を拡張する感じですかね。。

```
class _LearningParameter:
    positions_in_circuit: List[int]
    parameter_id: int
    value: float
    is_input: bool = field(default=False)
```
`_PositionDetail`クラスを作って、`List[int]`ではなく、`List[_PositionDetail]`で持たせる感じですかね。。

```
class _PositionDetail:
    gate_pos: int,
    coef: Optional[float]
```

**Comment by ikanago** [comment]
そうですね，それで `None` でない `coef` をもつときはそれをかけてやればうまくいきそうです．
