### ISSUE TITLE
Use numpy's ndarray instead of `List` for type hints

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#179]
現在 `x: List[List[float]]` や `y: List[int]` のような型ヒントを書いていますが、`numpy.typing.NDArray` あるいは `numpy.ndarray` に置き換えようと思います．
`List` と書いているのに実際には numpy の ndarray が入っていることが多く，型ヒントの意味が薄くなっているためです．

**Comment by WATLE** [comment]
ほんとだ

**Comment by WATLE** [comment]
ありがとう
