### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#188]
テストカバレッジの計測・可視化

**Comment by ikanago** [comment]
こんな感じの html が生成されることは確認できましたが，どうやってホストしようかなと考えています
<img width="962" alt="image" src="https://user-images.githubusercontent.com/28985004/169952825-0e8d8970-5baf-4ab5-a49b-b24fb45ef96e.png">

**Comment by Hiroya-W** [comment]
カバレッジ、PR時にグラフィカルに見れると嬉しいですよね
Codecovとか使ってみるとCIと統合もしやすそう？pytestとの連携もあるようです
https://about.codecov.io/tool/pytest/

**Comment by ikanago** [comment]
やっぱり Codecov が便利そうですね．試してみます!

**Comment by Hiroya-W** [comment]
ありがとうございます！お願いします！

**Comment by ikanago** [comment]
Codecov の GitHub App をインストールして，カバレッジのデータをアップロードしてみました．
https://codecov.io/gh/Qulacs-Osaka/scikit-qulacs/tree/459ab477d3a8e25772e5d2743adcf55942d7f208
