### ISSUE TITLE
Farhi の QNN 回路の実装

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#19]
Edward Farhi という有名な研究者 (量子アニーリングの提唱者) がいて、その人が提案した QNN の回路がある。それを分類・回帰に実装してみる。
https://arxiv.org/pdf/1802.06002.pdf のFigure 1

**Comment by WATLE** [comment]
Fig1の回路だけで、他は真似しなくてもいいんですよね？

**Comment by WATLE** [comment]
もどきを実装して、regに適用した。
