### ISSUE TITLE
`QNNRegressor.n_outputs >= 2` のテストケース

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#202]
`QNNRegressor.n_outputs >= 2` の場合のテストケースがなかったので追加しようと思うんですが、`f(x, y) = (sin(x + y), cos(x - y))` みたいな2出力関数の回帰とかをやるとよさそうですかね?
https://app.codecov.io/gh/Qulacs-Osaka/scikit-qulacs/blob/main/skqulacs/qnn/regressor.py

**Comment by ikanago** [comment]
テストを書いてみたんですが、まったく収束しなくて kill されてしまいますね...
https://github.com/Qulacs-Osaka/scikit-qulacs/blob/202-multi-value-regression/tests/test_qnn_regressor.py

**Comment by forest1040** [comment]
自分もみてみます。

**Comment by forest1040** [comment]
自分の環境では普通に実行できました。。

```
def main() -> None:
    x_test, y_test, y_pred = test_noisy_sine_two_vars(Bfgs(), 50)
    plt.plot(x_test, y_test, "o", label="Test")
    plt.plot(x_test, y_pred, "o", label="Prediction")
    plt.legend()
    plt.show()
    plt.savefig("test2.png")

``
![test2](https://user-images.githubusercontent.com/127030/178891489-a319eac2-30e8-4e36-96b7-1ed9b60ac0e8.png)
`

**Comment by ikanago** [comment]
それはもとからあって正常に動いてる2入力1出力のテストなんですが，いま動かないのは2入力**2出力**の `test_noisy_two_vars_two_outputs()` のほうですね

**Comment by forest1040** [comment]
なるほど！
[test_noisy_two_vars_two_outputs()](https://github.com/Qulacs-Osaka/scikit-qulacs/blob/db2501e27667f1ccbd087bd9ed2ec51de5a73cb4/tests/test_qnn_regressor.py#L33) 見てみます。

**Comment by ikanago** [comment]
190行目で `print(grad)` しても一度しか表示されないので，`_cost_func_grad` で呼ばれてる `backprop` で詰まってるっぽいですね

**Comment by ikanago** [comment]
出力次元数のぶんだけ `QNNRegressor` を用意して動かせばいいので，多出力をサポートしないという選択肢もありえますね

**Comment by ikanago** [comment]
`f"Z {i}"` にしたら loss の値も同じになりました．
これなんで今まで動いてたんでしょうね...
Python はこれを黙って実行しちゃうのでつらいですね...

**Comment by forest1040** [comment]
> これなんで今まで動いてたんでしょうね...

n_outputsが2以上になるケースが少ないから、発覚しなかったんですかね。。
