### ISSUE TITLE
Deprecate `QNN`

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#216]
skqulacs/qnn/qnn_base.py にある抽象クラスの `QNN` ですが，`QNNClasifier` や `QNNRegressor` などを抽象化するメリットがあまりないと思うので，削除しても問題ないと思っています．

**Comment by forest1040** [comment]
確かに今のところ、`QNN`はインターフェイスを定義しているだけですね。。
共通インターフェイスである必要が今のところないので、削除してよさそうですね。
そういう時がくれば復活させればいいですし。。
