### ISSUE TITLE
ソフトマックス関数対応の検討

### ISSUE THREAD

**Issue by forest1040** [Qulacs-Osaka/scikit-qulacs#223]
現在、分類の場合、量子ビット数に１対１対応になっているので
量子ビット数分の分類しかよい精度でできないはず。
回路の期待値に対して、最後にソフトマックス関数で分類するようにすればできるかも。

**Comment by WATLE** [comment]
これ、つまり、　3bitで4つの分類をするために、　期待値の実数値が-1.0~-0.5 →① -0.5~0→② 0~0.5→③ 0.5~1→④　みたいにしたいということですか？

それとも、測定を2進法でとって、　上2bitが00→① 01→②  10→③ 11→④ ですか？

**Comment by forest1040** [comment]
期待値の実数値が-1.0~-0.5 →① -0.50→② 00.5→③ 0.5~1→④
でよいかと思います。

**Comment by WATLE** [comment]
この「期待値」は1ビットからすべて取ってきますか？

**Comment by forest1040** [comment]
回路全体の期待値でいいかなと思っています。

**Comment by WATLE** [comment]
ん、回路全体とは、　3bitなら0～7 を取る値ですか？　それとも、各bitが-1～1を取り、　その合計値や平均値ですか？

**Comment by forest1040** [comment]
各bitが-1～1を取って、その平均値でいいかなと思います。

**Comment by WATLE** [comment]
冷静に考えてきつい気がしてきました、　例えば①か④かで迷ったとき、　①なら-1,-1,-1 、④なら1,1,1 を取る必要がありますが、　その境目だと回路が0,0,0になり、②や③になってしまう気がします

**Comment by WATLE** [comment]
測定を2進法でとって、最大2^n 択から選ぶパターンなら　割と行ける気がしてきました(それでも勾配消失などが大変ではありますが)

**Comment by forest1040** [comment]
なるほど。それでお願いします。

**Comment by WATLE** [comment]
もともと量子ビット分の分類だったのが、量子ビット+1 になります。　1つ増加するだけでいいんですか？

**Comment by WATLE** [comment]
分類しなきゃいけない数がビット数より明らかに多い場合を想定していたハズなのに、　分類数=ビット数+1 では不足するのでは？

**Comment by forest1040** [comment]
すみません。自分がソフトマックス関数を勘違いしていたのですが、
分類数でスライスしておけば、期待値で該当する分類に割り当てられるかと思いました。

**Comment by WATLE** [comment]
はい。　それでは、　これまで通りの実装で行きます。

**Comment by forest1040** [comment]
例えば、A,B,C〜Jまでの10個に分類したい場合、
量子ビットを4個使って、|0000>が0.24だった場合、Cとする事を想定しています。

**Comment by forest1040** [comment]
すみません。ようやく理解しました。
学習がうまく進まないということですね。。
現状の実装の2進数方式でお願いします！

**Comment by WATLE** [comment]
一応、ABC... が順序を持つなど、　AC間の違いがAB間やBC間よりも大きい　などであれば成り立ちますが、そうではなさそうです
