### ISSUE TITLE
学習結果を保存する機能

### ISSUE THREAD

**Issue by forest1040** [Qulacs-Osaka/scikit-qulacs#224]
学習したパラメータをファイルに保存して、読み込む機能を追加する

**Comment by ikanago** [comment]
pickle でモデルごと固めてやればよさそうですね．
pytorch とかを参考にしながらやってみようと思います．

**Comment by forest1040** [comment]
お願いします！

**Comment by forest1040** [comment]
データの保存と読み込みは、Python層でやるのでよいと思います。シリアライズ等あるでしょうし。
VQEとか用にPython便利ライブラリを用意した方がいい気がしてきました。（別チケット）

**Comment by ikanago** [comment]
保存してロードしたモデルともとのモデルが等値(パラメータや `Solver` などの値が等しい)であることを確認するテストを書こうとしているのですが，デフォルトの `__eq__()` メソッドは `is` での比較であり不十分です．
そこで各モデルとそのメンバ変数のクラスに `__eq__()` を実装して回る必要がありそうです．
`dataclass` にしてしまえば自動で `__eq__()` が実装されるので，この際すべて `dataclass` にしてしまおうかなとも思っています．

**Comment by ikanago** [comment]
#230
