### ISSUE TITLE
Implement `Dataloader`

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#256]
SSIA

**Comment by Gruntrexpewrus** [comment]
I want to help, of course! Do you want to use `PyTorch` or you want to define completely a qulacs_loader?

**Comment by ikanago** [comment]
Adding PyTorch as dependency and using `DataLoader` from it is the easiest solution, but it is too complex for current demand.
I'm going to implement a prototype and merge it if it is simple enough. When it grows more complex in the future, we will consider to use the one in PyTorch.

**Comment by Gruntrexpewrus** [comment]
I just think that including later the one from PyTorch can make Quantum Machine Learning super comfortable, since we can basically use any ML dataset without any problem.
