### ISSUE TITLE
https://arxiv.org/abs/2012.03924 の再現

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#34]
https://arxiv.org/abs/2012.03924 を再現したい。必要なモジュール群を作りたい。

**Comment by WATLE** [comment]
これ、　既存の機械学習とNISQの融合だけど、機械学習、特にGANに詳しい人が欲しい。　既存の機械学習に関して素人すぎてよくわからない。

**Comment by shim98a** [comment]
取り組んでみようと思います

よくある量子GANは
- GeneratorかDiscriminatorのどちらか一方が量子回路でもう一方は古典の深層学習モデル
- GeneratorもDiscriminatorの両方に量子回路を使う
となっているが、上記論文の手法(QC-ANN)はどちらにも属さないので、QC-ANN専用のクラスを作りたいなら以下のような仕様?

仕様の一例
```python3
import torch

class QCANN:
    def __init__(
        self,
        born_circuit: LearningCircuit,
        discriminator: torch.nn.Module,
        generator: torch.nn.Module,
        ...
    ) -> None:
```
discriminatorとgeneratorにはpytorchかtensorflow(上記例はpytorch)のモデルを入れるような例だが、ユーザーがpytorchを使ってモデルを組まなければいけない。それの代替案として、古典の方は簡単なDCGANの構造と固定して、ユーザーは層の数とかだけを指定できるようにするやり方もある。
```python3

class QCANN:
    def __init__(
        self,
        born_circuit: LearningCircuit,
        discriminator_num_layers: Sequence[int],
        generator_num_layers: Sequence[int],
        ...
    ) -> None:
```
みたいな…？

**Comment by kosukemtr** [comment]
あんまり深く読まずに適当に投げてしまったんですが、確かにこれ結構ややこしくて難しそうですね。長期計画になりそうですね
