### ISSUE TITLE
jupyterは3.7なのでcannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by WATLE** [Qulacs-Osaka/scikit-qulacs#36]
タイトルの通り、　jupyterのバージョンにtypingのLiteralが対応していない。

**Comment by WATLE** [comment]
https://stackoverflow.com/questions/61206437/importerror-cannot-import-name-literal-from-typing

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
したらよさそう？

**Comment by ikanago** [comment]
この処理を skqulacs/typing.py に書いてそこから import するようにします
