### ISSUE TITLE
 QNNのベースクラスについて

### ISSUE THREAD

**Issue by WATLE** [Qulacs-Osaka/scikit-qulacs#75]
classもregも、fitとpredictの引数が、QNN(ベースクラス)のそれと大幅に違う。なのに、動く。なぜ？　また、 QNNのベースクラスを変更、またはいっそベースクラス廃止してもいいと思う。

**Comment by ikanago** [comment]
引数が違うのに動くのは型チェックをしていないからです．
mypy というツールで型チェックが一応できるので導入を検討しています．

ベースクラスの存在意義ですが，確かにいらない気もします．
モデルを抽象的に扱いたいなら必要ですが，ユーザがモデルを呼び出すだけなので抽象化する意味があまりないですね．
