### ISSUE TITLE
Add manual to embed jupyter notebook in the document

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#77]

**Comment by herring101** [comment]
これってどんな経緯で作られたissueなんでしょうか？

**Comment by ikanago** [comment]
ドキュメントに jupyter notebook を埋め込む方法を明記する issue だったんですが，[CONTRIBUTING.md](https://github.com/Qulacs-Osaka/scikit-qulacs/blob/3d7153fb966189486196a491aed2a65436d992bf/CONTRIBUTING.md) の最後にすでに記載してあるので閉じます．リマインドありがとうございます 🙏
