### ISSUE TITLE
Use optimizers from scikit-learn

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#79]
`skqulacs.ann.regressor.py` などで Adam がベタ書きされているが、これを scikit-learn の `SGDOptimizer, AdamOptimizer` に変えてスッキリさせたい

**Comment by WATLE** [comment]
scikit-learn の SGDOptimizer, AdamOptimizer ,公式サイトの検索機能で調べても情報が出てきませんでした。　詳しく教えて下さい。

**Comment by kosukemtr** [comment]
確かに出てこなかった。ソース読むしかない説：https://github.com/scikit-learn/scikit-learn/blob/0d378913be6d7e485b792ea36e9268be31ed52d0/sklearn/neural_network/_stochastic_optimizers.py

**Comment by WATLE** [comment]
ソースファイルに_がついているし、内部で使うことを想定されていそう
scikit-learnのバージョンアップで変わる可能性が高いし、　現状も2次元以上の配列に対してしか動かない。
