### ISSUE TITLE
scikit-learn-like API 

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#80]
`QNNClassifier` や `QNNRegressor` などのクラスのインターフェースを scikit-learn に合わせたい。具体的には https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html に合わせたい。

**Comment by WATLE** [comment]
大まかには合わせたはずだけど、唯一異なる点として、LearningCircuitを要求する部分があると思われる。
昔はLearningCircuitはQNNClass or QNNReg クラスが生成していた。

どうしますか? @ikanago

**Comment by kosukemtr** [comment]
あーこれは久保さんからの slack コメントで何か違うのかな？と思ったので反射的に立てた issue でした。とりあえず無視しといてください
