### ISSUE TITLE
Implement deep quantum circuit

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#81]
http://arxiv.org/abs/2111.02951 の量子回路の実装 & 再現

**Comment by WATLE** [comment]
QSVM用のcircuitのpre_defindに、新しい回路を用意すればよさそう

**Comment by WATLE** [comment]
論文をよんだので、コードが触れるようになれば実装します

**Comment by WATLE** [comment]
結局、fig3でをcircuitとして、QSVMですよね？

**Comment by WATLE** [comment]
ランダムな回転をするゲートが必要で、
2bitの回路に対してU(Θ) =exp(i/2 θxxX1X2 + i/2 θyyY1Y2 + i/2 θzzZ1Z2)が必要ですが、
これが何を表すのか全く分かりません

**Comment by WATLE** [comment]
結局,そのUの前後にランダムな1bitのやつをやっていて、自由度15だから、ランダムならなんでもいいのかな?

**Comment by WATLE** [comment]
できました
