### ISSUE TITLE
Add optioonal callback functions for fit

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#82]
qnn.fit などについて、訓練の様子を見られるように callback function を投げられるようにしたい。scipy.optimize.minimize の callback function と同じような感じで投げられると嬉しい。

**Comment by WATLE** [comment]
本家scikitを参考にしようとしたら、本家にはありませんでした

**Comment by WATLE** [comment]
ちなみに本家では、maxiterを少なくしてして、　その分複数回fitして、そのたびに正解率を取ってグラフにしているようです。
これはscikit-qulacsでも可能です

for
  fit
  print(正解率)

**Comment by WATLE** [comment]
いや、ダメでした　fitするたびにBFGSの履歴とか、Adamのモーメントとかが初期化される

されないように修正したほうがよさそう？

**Comment by WATLE** [comment]
https://qiita.com/hatt0519/items/315cd25d3eaae3217103

**Comment by WATLE** [comment]
callbackの使用例
https://github.com/Qulacs-Osaka/scikit-qulacs/commit/1bd2c16e8681931130386dd8136f31b590c69b05

**Comment by WATLE** [comment]
手元でcallback実装しました。　どうやってテストするか次考えます。

**Comment by kosukemtr** [comment]
#128 に入っているよう
