### ISSUE TITLE
Add visualization of pre-defined circuits on tutorials

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#83]
https://github.com/Qulacs-Osaka/qulacs-visualizer と接続して、ansatz を簡単に可視化できるようにしたい。

**Comment by WATLE** [comment]
quantumcircuitじゃなくて、LearningCircuitで持ってる(こっちは、ゲートの角度が内部パラメータと入力値の関数で表せる）からそのままだとvisと連携できないけど、できるようにしたい　という話か。面白そうです。

たぶん、LearningCircuitの中のParametricCircuitの中のquantumcircuitを表示するだけで、そこそこきれいになりそうな気もします

**Comment by WATLE** [comment]
冷静に考えると、ansatz等のデフォルトのゲートは自分でいじれないから、　どうせならデフォルトをvisualizeした画像を置くほうが親切なきもします

**Comment by kosukemtr** [comment]
> 冷静に考えると、ansatz等のデフォルトのゲートは自分でいじれないから、　どうせならデフォルトをvisualizeした画像を置くほうが親切なきもします

そのとおりだと思うので、visualizer 使って出力したゲートをまとめてチュートリアルページに追加しますか。

**Comment by ikanago** [comment]
@kosukemtr 
この issue 必要そうならやろうと思うんですが、どうでしょうか
