### ISSUE TITLE
Modify `LearningCircuit` class to handle generative model

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#84]
`LearningCircuit` は現在 `run()` メソッドに引数が必須となっているが、生成モデル等の場合入力データが無い場合がある。これに対応したい。具体的には `run()` に引数を与えなくても動くようにしたい。

**Comment by WATLE** [comment]
引数がない時の挙動は、runに空配列を渡したときと同じでよいはずだと思います。準備が整ったら実装します

**Comment by kosukemtr** [comment]
簡単な機能追加なので練習も兼ねて @herring101 さんにやってもらうのがいいと思いました

**Comment by kosukemtr** [comment]
#100
