### ISSUE TITLE
Use poetry and redefine unit test and linter setting

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/scikit-qulacs#88]

**Comment by ikanago** [comment]
型ヒントが抜けていたりして修正に時間がかかりそうなので，`[tool.pysent.lint]` で `enable_mypy = false` として mypy を一時的に省略したほうがよさそうです．
#87 で改めて型ヒントに対応するのが1つの案です．

**Comment by WATLE** [comment]
手元でだけpysentで型チェックできるようにできますか？

**Comment by ikanago** [comment]
CI では型チェックしない，みたいなことはできます．
