### ISSUE TITLE
arxiv: 2108.01039 の再現

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#96]
https://arxiv.org/abs/2108.01039 で使われている LearningCircuit の構成と実験結果の再現

**Comment by WATLE** [comment]
これで使われているLerningCircuitの構成を試してみましたが、スコアは非常に悪かったです。
defqsvが0.005程度のloss,deepqsvは0.003程度に対し、このqsvは0.025程度あります。

テストとの相性が悪い可能性も大いにありますが、スコアが低いのは事実です。
ほかのqsvのLearningCircuit の構成に比べて、QSV回路の形がシンプルすぎるのが敗因だと思います。
どうしますか?
・これと相性が悪くないテストを探す
・スコアが低いけど、scikit-qulacsに乗せる
・スコアが低いので、scikit-qulacsに入れない

**Comment by kosukemtr** [comment]
ブランチと結果を載せてみてもらってもいいですか？

**Comment by kosukemtr** [comment]
基本的に scikit-qulacs は論文を手軽に再現できることを目標に作りたいと思っているので、再現できていればそれで乗せればいいと思います

**Comment by WATLE** [comment]
large_qsvブランチにあります
large_qsvだけtestで許容lossが大きいのが、そういうことです

**Comment by kosukemtr** [comment]
#115

**Comment by WATLE** [comment]
Kosuke Mitarai  1分前
返信遅くなりしました。Fig. 5(a) と Fig. 5(c) です

Kosuke Mitarai  < 1分前
Fig.5(a) は特に\theta_r を Eq. (A1) にセットしてあげてください

**Comment by kosukemtr** [comment]
実装できたら Fig. 4(a) が再現できるか確かめてみていただけるとありがたいです。実験は scikit-learn の手書き文字 (https://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html) を使っていて、
> We learn to classify handwritten 2D images of digits ranging from 0 to 9. The dataset contains L = 1797 images of 8 × 8 pixels, where each pixel has an integer value between 0 and 16 [50]. We map the image to M = 64 dimensional feature vectors. For the YZ-CX PQC, we use all M = 64 features, whereas for the NPQC we perform a principal component analysis to reduce it to M = 36 features.

ということです。

**Comment by kosukemtr** [comment]
上の数値実験は新しいチュートリアルノートブックとして作っていただけるといいと思います
