### ISSUE TITLE
生成モデル　https://arxiv.org/abs/1804.04168 の再現

### ISSUE THREAD

**Issue by kosukemtr** [Qulacs-Osaka/scikit-qulacs#99]
生成モデルの例として https://arxiv.org/abs/1804.04168 を再現する。

**Comment by WATLE** [comment]
生成モデルとは何か理解しました。そこそこ時間はかかりそうですが、(1～2週間程度?) 作れそうです。

**Comment by WATLE** [comment]
とりかかります

**Comment by WATLE** [comment]
手が空いた時に進めます

**Comment by WATLE** [comment]
大体できて、バグもなさそうだけど、stripeでx=75%程度が限界です

**Comment by WATLE** [comment]
depth増やしたら85%まで行った

**Comment by WATLE** [comment]
stripeは安定しないのでテストから外した

**Comment by WATLE** [comment]
backpropの機能追加を利用するので、qulacs-osakaの新しいバージョンがリリースするのを待っています。
それがされたら、pull requestします。
